# .github/FUNDING.yml
# GitHub Sponsors configuration for AarambhDevHub

# GitHub Sponsors (your username)
github: AarambhDevHub

# Buy Me a Coffee (your username)
buy_me_a_coffee: aarambhdevhub

# Optional: Add other platforms later if needed
# ko_fi: aarambhdevhub
# patreon: aarambhdevhub
# custom: ["https://paypal.me/yourpaypal"]
